color: true
package: './package.json'
require: 'ts-node/register'
extension: ['js', 'cjs', 'mjs', 'ts']
spec:
  - 'test/**/*.test.ts'
watch-files:
  - 'test/**/*.test.js'
watch-ignore:
  - 'lib/vendor'